#Database configuration
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create




  flyway:
    url: jdbc:mysql://localhost:3306/blog
    baseline-version: 1
    password:
    user: root
    baseline-on-migrate: true

#general blog data
blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightForm: 2005



